Add support or internal deposit address
TuringAdvisoryGroup/tryrolljs pull request #259
Opened 2023-05-10 20:20 UTC by ashish-nikalje

## What's done
   - added api support for get platform deposit address for user
   - add api support for get platform user token balance
## How to test

## note
this should be get merged after  https://github.com/TuringAdvisoryGroup/roll-go/pull/3700

## Tasks

- [ ] Have you written tests for new code (if applicable)?
- [ ] Have you tested the changes on all the platforms?
  - [ ] iOS
  - [ ] Android
  - [ ] Web
- [ ] Have you added stories to demonstrate the new functionality (if there is any)?

## Demo (screenshots, recordings, etc.)

2023-05-11 11:31 UTC, diegonzs-roll requested changes
Great work here @ashish-nikalje

2023-05-11 11:31 UTC, diegonzs-roll commented on packages/api/src/user/user.ts
> +    method: 'get',
```suggestion
    method: 'GET',
```

2023-05-11 11:31 UTC, diegonzs-roll commented on packages/api/src/user/user.ts
> +    method: 'get',
```suggestion
    method: 'GET',
```

2023-05-11 11:31 UTC, diegonzs-roll commented on packages/api/src/user/user.ts
> +    method: 'get',
```suggestion
    method: 'GET',
```

2023-05-11 11:31 UTC, diegonzs-roll commented on packages/sdk/src/auth/sdk.ts
> +      console.log('response', response);
You can remove this console.log :)

2023-05-11 11:44 UTC, diegonzs-roll approved these changes

2023-06-14 13:09 UTC, marlon-wiprud commented
closing in favor of the updates made here which avoided some of the conflicts in this PR: https://github.com/TuringAdvisoryGroup/tryrolljs/pull/311

2023-06-14 13:09 UTC, closed without merging